name: Commitlint

on:
  workflow_call: {}

jobs:
  commitlint:
    name: "Commit messages (commitlint)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch commitlint config
        uses: actions/checkout@v4
        with:
          repository: QUBERAS/quality-standards
          path: .quality-standards
          sparse-checkout: configs/common/commitlint.config.js

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install commitlint
        run: npm install --save-dev @commitlint/cli @commitlint/config-conventional

      - name: Lint commits
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            npx commitlint \
              --config .quality-standards/configs/common/commitlint.config.js \
              --from "${{ github.event.pull_request.base.sha }}" \
              --to "${{ github.event.pull_request.head.sha }}" \
              --verbose
          else
            npx commitlint \
              --config .quality-standards/configs/common/commitlint.config.js \
              --from "${{ github.event.before }}" \
              --to HEAD \
              --verbose
          fi
