name: Commitlint

on:
  workflow_call: {}

jobs:
  commitlint:
    name: "PR title (conventional commits)"
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch commitlint config
        uses: actions/checkout@v4
        with:
          repository: QUBERAS/quality-standards
          path: .quality-standards
          sparse-checkout: configs/common/commitlint.config.js

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install commitlint
        run: npm install --save-dev @commitlint/cli @commitlint/config-conventional

      - name: Lint PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" | npx commitlint \
            --config ".quality-standards/configs/common/commitlint.config.js" \
            --verbose
